### ISSUE TITLE
仕様：有料アカウントが必要かも

### ISSUE THREAD

**Issue by takumah1234** [enpitut2021/chimimoryo_autumn#13]
https://pub.dev/packages/home_widget を読んでいると，以下の文章があった．
> You need to add a groupId to the App and the Widget Extension
> 
> Note: in order to add groupIds you need a paid Apple Developer Account

とのことらしい．また，読み進めたところ，以下の指示があった．

> For iOS, you need to call HomeWidget.setAppGroupId('YOUR_GROUP_ID'); Without this you won't be able to share data between your App and the Widget and calls to saveWidgetData and getWidgetData will return an error

どうやら，有料アカウントのGroupIDがWidgetとアプリケーションの通信に必要らしい．
ここら辺が詳しくないので，教えてもらいたい．

**Comment by sudame** [comment]
うーんなるほど、Group IDが必要なのか 🤔 
いきなりFlutterを絡めて考えるとしんどそうなので、一旦 Apple が公式で出してる iOS 向けのチュートリアル走ってみるとかしたほうが早そう
https://developer.apple.com/documentation/widgetkit/creating-a-widget-extension

**Comment by takumah1234** [comment]
なるほどね．
一応このタスクの担当は @ProfFunami だけど，僕がこの調査は引き受けた方がいい?
（タスク誰がするって話ここでしていいか分からないけど，一旦ここでします．）

**Comment by sudame** [comment]
誰でも良いのでバーッとやってみて結果を報告するのが幸せそう
僕も今日で一旦もろもろから開放されるので明日時間あればやってみます

**Comment by pfunami** [comment]
こちらmiro上のassign私から @takumah1234 （か誰か）に変更したいんだけれでよろしいだろうか（androidで力尽きた

**Comment by takumah1234** [comment]
了解．できるほどの時間が取れるか分からないけど（面接＋課題＋学会の準備）、一旦やれそうならやってみます。
他に確実に時間が取れる人がいるならお願いします。連絡ない限りは自分のタスクだと思っとくね

**Comment by takumah1234** [comment]
調べたり実装してみたりしたので，分かったことを報告．
結論から話すと，アプリとWidgetの通信にはやっぱり課金アカウントが必要みたい．
- https://ichi.pro/ios-apuri-to-sono-whijyettokan-de-no-obujyekuto-de-ta-no-kyoyu-176616291015729

ただ、他のサイトを見ているともしかしたら、サーバーから情報を取って来る方が一般的なのかも知れない．

- https://tech.naturalmindo.com/notwork_ios_widget/
- https://qiita.com/ryota2425/items/9b1759d9065ff528352c

ということで，アプリとWidgetの通信なしでやってみるといいのでは？という提案．
みなさん、どうでしょ?

**Comment by pfunami** [comment]
あーなるほど、そういう方法があるのか
qiitaの記事がわかりやすそうに見えたので、その方向で進むのは良いと思います
