### ISSUE TITLE
Flutterが実行できない

### ISSUE THREAD

**Issue by takumah1234** [enpitut2021/chimimoryo_autumn#20]
Flutterをandroidで実行しようとしたら、

> Running Gradle task 'assembleDebug'...

と出て、うまく動かなかった。
[このサイト](https://stackoverflow.com/questions/59516408/flutter-app-stuck-at-running-gradle-task-assembledebug/61489304)を見たら、`./gradlew cleanbuild`しろってことだったから、やったら、

> > Configure project :home_widget
> 
> WARNING: The option setting 'android.enableR8=true' is deprecated.
> It will be removed in version 5.0 of the Android Gradle plugin.
> You will no longer be able to disable R8
> 
> > Task :android_intent_plus:compileDebugJavaWithJavac
> 警告:[options] ソース値7は廃止されていて、今後のリリースで削除される予定です
> 警告:[options] ターゲット値7は廃止されていて、今後のリリースで削除される予定です
> 警告:[options] 廃止されたオプションについての警告を表示しないようにするには、-Xlint:オプションを使用します。
> 注意:/（一応のぞいてる）/flutter/.pub-cache/hosted/pub.dartlang.org/android_intent_plus-3.0.2/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.javaの操作は、未チェックまたは安全ではありません。
> 注意:詳細は、-Xlint:uncheckedオプションを指定して再コンパイルしてください。
> 警告3個
> ...
> > Task :android_intent_plus:compileDebugUnitTestJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':android_intent_plus:compileDebugUnitTestJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 1m 40s
> 95 actionable tasks: 92 executed, 3 up-to-date

みたいなエラーが出て、結局動かなかった．
どうしたらいいか教えて欲しい

**Comment by sudame** [comment]
最初の

```plain
Running Gradle task 'assembleDebug'...
```

はビルド中の表示(文字通り、タスクが走っている状態)なので放置で良かったはず。
初回や変更が多かったときや依存関係が変わったときは、いろいろなものを一気にビルドするのでかなり時間がかかる。気長に待つ必要がある。

**Comment by sudame** [comment]
後半のエラーは良く分からないけど

```
Task :android_intent_plus:compileDebugUnitTestJavaWithJavac FAILED
```

の上のあたりにエラー本体が出ているんじゃないかと思うのでそこを見てほしい、あるいは見せてほしい

**Comment by takumah1234** [comment]
`Running Gradle task 'assembleDebug'...`
のところは、これが一時続いた後、そのまま何も起こらずに終了するんだよね

**Comment by takumah1234** [comment]
sudameに教えてもらって、 #17 を参考にしたらできました〜
